name: CI

on:
  push:
    branches:
      - main
  

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory:
          - service1
          - service2
          - service3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd ${{ matrix.directory }}
          npm install

      - name: Run tests
        run: |
          cd ${{ matrix.directory }}
          npm test
