name: Node.js CI

on:
  push:
    branches: [ "main" ]
 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    # Add a step to check the directory structure
    - name: List Directory Structure for Debugging
      run: ls -R  # This will show you the entire directory structure, useful for debugging

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install Backend Dependencies
    - name: Install Backend Dependencies
      working-directory: ./campus-commune/backend  # Adjust if `campus-commune` is the root folder
      run: npm ci

    # Install Frontend Dependencies
    - name: Install Frontend Dependencies
      working-directory: ./campus-commune/frontend  # Adjust if `campus-commune` is the root folder
      run: npm ci

    # Build Frontend (if applicable)
    - name: Build Frontend
      working-directory: ./campus-commune/frontend
      run: npm run build --if-present

